// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4kOvmxWmYQAimHhX0c9O37MKNFj0f7zA',
    appId: '1:339620283678:web:e7d4559a2afb95df8f350f',
    messagingSenderId: '339620283678',
    projectId: 'collegecanteen-7226d',
    authDomain: 'collegecanteen-7226d.firebaseapp.com',
    storageBucket: 'collegecanteen-7226d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNg750maI_efIWyKqHvjjJg_AbeglY64w',
    appId: '1:339620283678:android:d99056f8473b10828f350f',
    messagingSenderId: '339620283678',
    projectId: 'collegecanteen-7226d',
    storageBucket: 'collegecanteen-7226d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASEM-1AVw1e9L139c8d1YNUFXCp2Ez-LA',
    appId: '1:339620283678:ios:b4780d32c05894368f350f',
    messagingSenderId: '339620283678',
    projectId: 'collegecanteen-7226d',
    storageBucket: 'collegecanteen-7226d.firebasestorage.app',
    iosBundleId: 'com.example.liftapp',
  );
}
